### ISSUE TITLE
Purchased API but site is broken and never received API key.

### ISSUE THREAD

**Issue by dj12djdjs** [partsapi/PartsAPI.Ru#1]

**Comment by autodatabases** [comment]
hi! yesterday it was mysql db corrupted, and few client`s orders was payed, but dont logged into the base. Can you write to info@partsapi.ru?

**Comment by dj12djdjs** [comment]
@samakin I've sent them messages a few times. The order was purchased at the beginning of February. I haven't heard anything back from.
